import { FrameworkDefinition } from '@/types';

export const frameworkDefinitions: Omit<FrameworkDefinition, 'id'>[] = [
  {
    name: 'six_thinking_hats',
    displayName: '六顶思考帽',
    description: '爱德华·德波诺的平行思维方法，从六个不同视角全面分析问题',
    category: '综合分析',
    phaseCount: 6,
    triggers: ['分析', '全面', '多角度', '综合', '评估', '决策'],
    phases: [
      {
        index: 0, name: 'white_hat', displayName: '白帽 - 数据与事实',
        description: '聚焦客观数据、已知事实和信息缺口',
        instruction: '请从白帽思维出发：只讨论客观事实和数据。我们掌握了哪些信息？还缺少什么数据？不要做主观判断。',
        roundCount: 1,
      },
      {
        index: 1, name: 'red_hat', displayName: '红帽 - 直觉与情感',
        description: '表达直觉反应、情绪感受、预感',
        instruction: '请从红帽思维出发：分享你的直觉反应和情感感受。不需要理由，直接说出你的第一感觉、担忧或兴奋之处。',
        roundCount: 1,
      },
      {
        index: 2, name: 'black_hat', displayName: '黑帽 - 风险与批判',
        description: '审慎思考、风险识别、可能的问题',
        instruction: '请从黑帽思维出发：扮演批判者角色。这个方案有什么风险？可能出什么问题？有哪些逻辑漏洞或隐患？',
        roundCount: 1,
      },
      {
        index: 3, name: 'yellow_hat', displayName: '黄帽 - 价值与乐观',
        description: '积极价值、潜在收益、最佳情景',
        instruction: '请从黄帽思维出发：探索积极面和潜在价值。最好的情况是什么？有哪些机会和优势？为什么这值得做？',
        roundCount: 1,
      },
      {
        index: 4, name: 'green_hat', displayName: '绿帽 - 创意与替代',
        description: '创造性思维、新想法、替代方案',
        instruction: '请从绿帽思维出发：发挥创造力。有没有全新的想法？能否换个角度思考？有什么非常规的解决方案？',
        roundCount: 1,
      },
      {
        index: 5, name: 'blue_hat', displayName: '蓝帽 - 总结与决策',
        description: '过程管理、总结发现、形成结论',
        instruction: '请从蓝帽思维出发：综合前面所有讨论，总结关键发现，提出行动建议和最终结论。',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'premortem',
    displayName: '事前验尸法',
    description: '假设项目已经失败，反向推导可能的失败原因并制定预防措施',
    category: '风险评估',
    phaseCount: 4,
    triggers: ['风险', '失败', '项目', '发布', '上线', '预防'],
    phases: [
      {
        index: 0, name: 'assume_failure', displayName: '假设失败',
        description: '假设项目已完全失败，描述失败的情景',
        instruction: '假设我们的计划已经彻底失败了。请生动地描述失败的情景：发生了什么？造成了多大的影响？请尽可能具体。',
        roundCount: 1,
      },
      {
        index: 1, name: 'brainstorm_causes', displayName: '头脑风暴失败原因',
        description: '列举所有可能导致失败的原因',
        instruction: '现在请头脑风暴：是什么原因导致了这个失败？列出所有可能的原因，包括技术、人员、流程、外部因素等。不要过滤，越多越好。',
        roundCount: 1,
      },
      {
        index: 2, name: 'prioritize_risks', displayName: '风险优先级排序',
        description: '对失败原因按发生概率和影响程度排序',
        instruction: '对上述失败原因进行优先级排序。评估每个原因的发生概率（高/中/低）和影响程度（高/中/低），找出最关键的几个风险。',
        roundCount: 1,
      },
      {
        index: 3, name: 'mitigation', displayName: '制定缓解方案',
        description: '针对高优先级风险制定预防和缓解措施',
        instruction: '针对排名靠前的风险，制定具体的预防措施和应急方案。每个风险至少给出一个预防措施和一个应急方案。',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'swot',
    displayName: 'SWOT 分析',
    description: '从优势、劣势、机会、威胁四个维度全面评估战略方案',
    category: '战略规划',
    phaseCount: 4,
    triggers: ['战略', '竞争', '市场', '商业', '优势', '劣势'],
    phases: [
      {
        index: 0, name: 'strengths', displayName: '优势 (Strengths)',
        description: '识别内部优势和核心竞争力',
        instruction: '分析内部优势：我们有哪些独特优势？核心竞争力是什么？哪些资源和能力是别人难以复制的？',
        roundCount: 1,
      },
      {
        index: 1, name: 'weaknesses', displayName: '劣势 (Weaknesses)',
        description: '识别内部不足和改进空间',
        instruction: '分析内部劣势：我们在哪些方面不足？有什么已知的短板？哪些能力需要补强？竞争对手在哪些方面比我们做得好？',
        roundCount: 1,
      },
      {
        index: 2, name: 'opportunities', displayName: '机会 (Opportunities)',
        description: '识别外部环境中的机遇',
        instruction: '分析外部机会：市场上有哪些趋势对我们有利？有没有尚未开发的新机会？竞争格局有什么变化可以利用？',
        roundCount: 1,
      },
      {
        index: 3, name: 'threats', displayName: '威胁 (Threats)',
        description: '识别外部环境中的威胁和挑战',
        instruction: '分析外部威胁：面临哪些竞争压力？有什么不利的市场或政策变化？技术变革可能带来什么风险？',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'five_whys',
    displayName: '五个为什么',
    description: '通过连续追问"为什么"来挖掘问题的根本原因',
    category: '根因分析',
    phaseCount: 5,
    triggers: ['原因', '根因', '为什么', '问题', '故障', '排查'],
    phases: [
      {
        index: 0, name: 'why_1', displayName: '第一个为什么',
        description: '针对表面现象提出第一个为什么',
        instruction: '面对这个问题，让我们追问第一个"为什么"：这个问题/现象为什么会发生？请给出直接原因。',
        roundCount: 1,
      },
      {
        index: 1, name: 'why_2', displayName: '第二个为什么',
        description: '对第一层原因继续追问',
        instruction: '针对上一轮提到的原因，继续追问第二个"为什么"：这些原因又是为什么会出现的？',
        roundCount: 1,
      },
      {
        index: 2, name: 'why_3', displayName: '第三个为什么',
        description: '对第二层原因继续深入',
        instruction: '继续深入，第三个"为什么"：前面提到的深层原因又是什么造成的？开始触及系统性问题了吗？',
        roundCount: 1,
      },
      {
        index: 3, name: 'why_4', displayName: '第四个为什么',
        description: '接近根本原因',
        instruction: '第四个"为什么"：我们是否已经接近根本原因？这些原因背后是否存在共同的系统性因素？',
        roundCount: 1,
      },
      {
        index: 4, name: 'why_5', displayName: '第五个为什么 + 解决方案',
        description: '揭示根本原因并提出解决方案',
        instruction: '最后一个"为什么"：总结根本原因是什么？基于根因分析，提出针对性的解决方案，而非仅治标。',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'scamper',
    displayName: 'SCAMPER 创新法',
    description: '通过七种创新思维技巧系统性地产生新想法',
    category: '创意创新',
    phaseCount: 7,
    triggers: ['创新', '创意', '产品', '设计', '改进', '新功能'],
    phases: [
      {
        index: 0, name: 'substitute', displayName: '替换 (Substitute)',
        description: '能替换哪些元素？',
        instruction: '思考替换：哪些组件、材料、流程或人员可以被替换？用什么替代会更好？有没有替代方案能简化或增强？',
        roundCount: 1,
      },
      {
        index: 1, name: 'combine', displayName: '组合 (Combine)',
        description: '能与什么组合？',
        instruction: '思考组合：哪些功能、想法或产品可以组合在一起？跨界融合能创造什么新价值？',
        roundCount: 1,
      },
      {
        index: 2, name: 'adapt', displayName: '适应 (Adapt)',
        description: '能从哪里借鉴？',
        instruction: '思考适应：其他行业有什么好的做法可以借鉴？历史上有什么类似的成功案例？能否将其他领域的方法改造使用？',
        roundCount: 1,
      },
      {
        index: 3, name: 'modify', displayName: '修改 (Modify)',
        description: '能如何放大或缩小？',
        instruction: '思考修改：能放大、缩小、增多或减少什么？改变形状、颜色、顺序、频率等会怎样？',
        roundCount: 1,
      },
      {
        index: 4, name: 'put_to_other_use', displayName: '挪用 (Put to other use)',
        description: '还能用在哪些场景？',
        instruction: '思考挪用：现有的东西还能用在什么新场景？如果换个目标用户群体会怎样？有没有意想不到的用途？',
        roundCount: 1,
      },
      {
        index: 5, name: 'eliminate', displayName: '消除 (Eliminate)',
        description: '能去掉什么？',
        instruction: '思考消除：哪些步骤、功能或组件可以去掉？简化到极致会是什么样子？什么是真正核心的、不可去掉的？',
        roundCount: 1,
      },
      {
        index: 6, name: 'reverse', displayName: '逆转 (Reverse)',
        description: '能否颠倒或重新排列？',
        instruction: '思考逆转：如果完全反过来做会怎样？颠倒顺序、角色互换、逆向思维能带来什么新洞察？',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'red_blue_team',
    displayName: '红蓝对抗',
    description: '通过攻击方（红队）和防御方（蓝队）的对抗来测试方案的健壮性',
    category: '压力测试',
    phaseCount: 3,
    triggers: ['安全', '测试', '攻击', '防御', '漏洞', '对抗'],
    phases: [
      {
        index: 0, name: 'red_team', displayName: '红队攻击',
        description: '红队视角：发现并利用所有弱点',
        instruction: '你现在是红队（攻击方）。请全力找出方案中的所有漏洞、弱点和可被利用的缺陷。越尖锐越好，不要留情面。',
        roundCount: 1,
      },
      {
        index: 1, name: 'blue_team', displayName: '蓝队防御',
        description: '蓝队视角：针对攻击制定防御策略',
        instruction: '你现在是蓝队（防御方）。针对红队发现的每一个漏洞和攻击面，提出具体的防御措施和改进方案。',
        roundCount: 1,
      },
      {
        index: 2, name: 'assessment', displayName: '综合评估',
        description: '综合红蓝两方观点，形成改进方案',
        instruction: '综合评估阶段：总结红蓝对抗的结果。哪些风险已得到有效缓解？还有哪些残留风险？给出最终的安全/可靠性评级和改进建议。',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'delphi',
    displayName: '德尔菲法',
    description: '通过多轮独立发表意见-反馈-收敛的过程达成专家共识',
    category: '共识构建',
    phaseCount: 3,
    triggers: ['共识', '专家', '预测', '估算', '评估', '一致'],
    phases: [
      {
        index: 0, name: 'independent_opinions', displayName: '独立意见',
        description: '每个专家独立发表观点，不受他人影响',
        instruction: '请独立发表你的专业意见。不要受其他人影响，基于你的专业知识和经验给出判断。包含你的核心观点、依据和置信度。',
        roundCount: 1,
      },
      {
        index: 1, name: 'feedback_revision', displayName: '反馈与修正',
        description: '看到他人意见后，反思并修正自己的观点',
        instruction: '现在你已经看到了其他专家的意见。请反思你的原始观点：有哪些是你之前没考虑到的？是否需要修正你的判断？给出修正后的意见和理由。',
        roundCount: 1,
      },
      {
        index: 2, name: 'convergence', displayName: '共识收敛',
        description: '总结共识与分歧，形成最终结论',
        instruction: '最终收敛阶段：总结各方共识点和仍存的分歧。对于分歧，分析原因并提出折中方案或进一步验证的方法。形成最终建议。',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'devils_advocate',
    displayName: '魔鬼代言人',
    description: '系统性地挑战和反驳方案以提升决策质量',
    category: '决策质量',
    phaseCount: 3,
    triggers: ['反驳', '挑战', '质疑', '辩论', '群体思维', '决策质量'],
    phases: [
      {
        index: 0, name: 'proposal', displayName: '提案陈述',
        description: '清晰完整地陈述提案和论据',
        instruction: '请对讨论主题给出你的最佳提案。包含核心主张、关键假设、预期收益和实施路径。尽可能有说服力。',
        roundCount: 1,
      },
      {
        index: 1, name: 'systematic_critique', displayName: '系统反驳',
        description: '魔鬼代言人角色：系统性地挑战每一个论点',
        instruction: '作为魔鬼代言人，系统性地挑战前面的提案。质疑每一个假设，寻找逻辑漏洞，提出反例和替代解释。目标不是否定，而是暴露盲点。',
        roundCount: 1,
      },
      {
        index: 2, name: 'strengthened_proposal', displayName: '强化提案',
        description: '吸收批评后加强原始提案',
        instruction: '综合前面的反驳意见，提出强化后的方案。哪些原假设需要修正？哪些风险需要补充措施？最终方案如何变得更加稳健？',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'design_thinking',
    displayName: '设计思维',
    description: '以用户为中心的创新方法论，通过五个阶段解决复杂问题',
    category: '用户导向',
    phaseCount: 5,
    triggers: ['用户', '体验', '设计', '产品设计', '需求', '痛点'],
    phases: [
      {
        index: 0, name: 'empathize', displayName: '共情',
        description: '深入理解用户需求、痛点和场景',
        instruction: '共情阶段：深入探讨目标用户是谁？他们的真实需求和痛点是什么？他们在什么场景下遇到这个问题？尝试站在用户角度思考。',
        roundCount: 1,
      },
      {
        index: 1, name: 'define', displayName: '定义',
        description: '明确核心问题和设计挑战',
        instruction: '定义阶段：基于共情发现，用一句话清晰定义核心问题。谁需要什么，因为为什么？确定设计挑战和约束条件。',
        roundCount: 1,
      },
      {
        index: 2, name: 'ideate', displayName: '创意',
        description: '发散思维，产生大量解决方案',
        instruction: '创意阶段：针对定义的问题，尽可能多地产生解决方案。不要自我审查，大胆想象。追求数量和多样性。',
        roundCount: 1,
      },
      {
        index: 3, name: 'prototype', displayName: '原型',
        description: '选择最佳方案，描述原型方案',
        instruction: '原型阶段：从创意中选出最有潜力的方案，描述一个可快速验证的原型。它长什么样？核心功能是什么？最小可行产品是什么？',
        roundCount: 1,
      },
      {
        index: 4, name: 'test', displayName: '测试',
        description: '设计测试方案，预判用户反馈',
        instruction: '测试阶段：如何验证这个原型方案？设计测试方案，预判用户可能的反馈。成功指标是什么？如何迭代改进？',
        roundCount: 1,
      },
    ],
  },
  {
    name: 'first_principles',
    displayName: '第一性原理',
    description: '回归基本事实和公理，通过解构和重建来找到突破性方案',
    category: '突破创新',
    phaseCount: 3,
    triggers: ['本质', '原理', '底层', '重新思考', '突破', '颠覆'],
    phases: [
      {
        index: 0, name: 'identify_assumptions', displayName: '识别假设',
        description: '列出所有隐含的假设和常规认知',
        instruction: '识别假设：关于这个问题，行业/常识中存在哪些"理所当然"的假设？我们不假思索接受了哪些前提？将它们全部列出来。',
        roundCount: 1,
      },
      {
        index: 1, name: 'deconstruct', displayName: '解构本质',
        description: '用物理学思维拆解到最基本的事实',
        instruction: '解构本质：剥去所有假设后，最底层的事实和原理是什么？像物理学家一样，只保留不可再分的基本事实。哪些假设经不起检验？',
        roundCount: 1,
      },
      {
        index: 2, name: 'reconstruct', displayName: '重建方案',
        description: '从基本事实出发，重新构建解决方案',
        instruction: '重建方案：从基本事实出发，不带任何预设地重新构建解决方案。如果我们完全从零开始，最优的方案会是什么？',
        roundCount: 1,
      },
    ],
  },
];
